-- AlterTable
ALTER TABLE "AiRequestLog" ADD COLUMN IF NOT EXISTS "model" TEXT NOT NULL DEFAULT '';
ALTER TABLE "AiRequestLog" ADD COLUMN IF NOT EXISTS "cost" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "ClinicalNote" ADD COLUMN IF NOT EXISTS "keyPoints" JSONB;
ALTER TABLE "ClinicalNote" ADD COLUMN IF NOT EXISTS "visitSummary" TEXT;
